steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/coursera-etl:latest', '.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/coursera-etl:latest']
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'run', 'deploy', 'coursera-etl',
         '--image', 'gcr.io/$PROJECT_ID/coursera-etl:latest',
         '--platform', 'managed',
         '--region', 'us-central1',
         '--allow-unauthenticated',
         '--set-env-vars', 'BIGQUERY_DATASET=coursera_data,BIGQUERY_TABLE=courses,GCS_BUCKET=chess_hs_bucket-1',
         '--memory', '1Gi']
  timeout: '600s'

images: ['gcr.io/$PROJECT_ID/coursera-etl:latest']